### ISSUE TITLE
Problems with Rails 7.0.3 Ruby 3.0.4 and stronger_parameter 2.17.0

### ISSUE THREAD

**Issue by blassoto** [zendesk/stronger_parameters#106]
Hello everyone, I've a next error when validation is unsuccessful, thanks!!:

ArgumentError at /api/v1/public/webhooks
========================================

wrong number of arguments (given 2, expected 5)

> To access an interactive console with this error, point your browser to: /__better_errors

app/controllers/api/v1/public/webhooks_controller.rb, line 18
-------------------------------------------------------------

``` ruby
   13   
   14           private
   15   
   16           def update_params
   17             params.require(:webhook)
>  18                   .permit(channel: Parameters.enum('amipass'),
   19                           url: Parameters.string, authorization_header: Parameters.string)
   20           end
   21         end
   22       end
   23     end
```

App backtrace
-------------

 - app/controllers/api/v1/public/webhooks_controller.rb:18:in `update_params'
 - app/controllers/api/v1/public/webhooks_controller.rb:10:in `update'

Full backtrace
--------------

 - activesupport (7.0.3) lib/active_support/notifications/instrumenter.rb:62:in `initialize'
 - actionpack (7.0.3) lib/action_dispatch/middleware/server_timing.rb:16:in `new'
 - actionpack (7.0.3) lib/action_dispatch/middleware/server_timing.rb:16:in `block in call'
 - activesupport (7.0.3) lib/active_support/notifications/fanout.rb:225:in `publish'
 - activesupport (7.0.3) lib/active_support/notifications/fanout.rb:80:in `block in publish'
 - activesupport (7.0.3) lib/active_support/notifications/fanout.rb:91:in `block in iterate_guarding_exceptions'
 - activesupport (7.0.3) lib/active_support/notifications/fanout.rb:90:in `each'
 - activesupport (7.0.3) lib/active_support/notifications/fanout.rb:90:in `iterate_guarding_exceptions'
 - activesupport (7.0.3) lib/active_support/notifications/fanout.rb:80:in `publish'
 - activesupport (7.0.3) lib/active_support/notifications.rb:197:in `publish'
 - stronger_parameters (2.17.0) lib/stronger_parameters/parameters.rb:163:in `block in hash_filter_with_stronger_parameters'
 - stronger_parameters (2.17.0) lib/stronger_parameters/parameters.rb:143:in `each_key'
 - stronger_parameters (2.17.0) lib/stronger_parameters/parameters.rb:143:in `hash_filter_with_stronger_parameters'
 - actionpack (7.0.3) lib/action_controller/metal/strong_parameters.rb:623:in `block in permit'
 - actionpack (7.0.3) lib/action_controller/metal/strong_parameters.rb:618:in `each'
 - actionpack (7.0.3) lib/action_controller/metal/strong_parameters.rb:618:in `permit'
 - app/controllers/api/v1/public/webhooks_controller.rb:18:in `update_params'
 - app/controllers/api/v1/public/webhooks_controller.rb:10:in `update'
 - actionpack (7.0.3) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
 - actionpack (7.0.3) lib/abstract_controller/base.rb:215:in `process_action'
 - actionpack (7.0.3) lib/action_controller/metal/rendering.rb:53:in `process_action'
 - actionpack (7.0.3) lib/abstract_controller/callbacks.rb:234:in `block in process_action'
 - activesupport (7.0.3) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
 - audited (5.0.2) lib/audited/sweeper.rb:16:in `around'
 - activesupport (7.0.3) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
 - audited (5.0.2) lib/audited/sweeper.rb:16:in `around'
 - activesupport (7.0.3) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
 - activesupport (7.0.3) lib/active_support/callbacks.rb:138:in `run_callbacks'
 - actionpack (7.0.3) lib/abstract_controller/callbacks.rb:233:in `process_action'
 - actionpack (7.0.3) lib/action_controller/metal/rescue.rb:22:in `process_action'
 - actionpack (7.0.3) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
 - activesupport (7.0.3) lib/active_support/notifications.rb:206:in `block in instrument'
 - activesupport (7.0.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 - activesupport (7.0.3) lib/active_support/notifications.rb:206:in `instrument'
 - actionpack (7.0.3) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
 - actionpack (7.0.3) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
 - activerecord (7.0.3) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
 - actionpack (7.0.3) lib/abstract_controller/base.rb:151:in `process'
 - actionpack (7.0.3) lib/action_controller/metal.rb:188:in `dispatch'
 - actionpack (7.0.3) lib/action_controller/metal.rb:251:in `dispatch'
 - actionpack (7.0.3) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
 - actionpack (7.0.3) lib/action_dispatch/routing/route_set.rb:32:in `serve'
 - actionpack (7.0.3) lib/action_dispatch/journey/router.rb:50:in `block in serve'
 - actionpack (7.0.3) lib/action_dispatch/journey/router.rb:32:in `each'
 - actionpack (7.0.3) lib/action_dispatch/journey/router.rb:32:in `serve'
 - actionpack (7.0.3) lib/action_dispatch/routing/route_set.rb:852:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - bullet (7.0.2) lib/bullet/rack.rb:12:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - rails-settings-cached (2.8.2) lib/rails-settings/middleware.rb:9:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - rack-attack (6.6.1) lib/rack/attack.rb:103:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/rack/browser_monitoring.rb:33:in `traced_call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - rack-attack (6.6.1) lib/rack/attack.rb:110:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - versionist (2.0.1) lib/versionist/middleware.rb:39:in `_call'
 - versionist (2.0.1) lib/versionist/middleware.rb:17:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - rack (2.2.3.1) lib/rack/etag.rb:27:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - rack (2.2.3.1) lib/rack/conditional_get.rb:40:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - rack (2.2.3.1) lib/rack/head.rb:12:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - activerecord (7.0.3) lib/active_record/migration.rb:603:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - actionpack (7.0.3) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
 - activesupport (7.0.3) lib/active_support/callbacks.rb:99:in `run_callbacks'
 - actionpack (7.0.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - actionpack (7.0.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - actionpack (7.0.3) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - rollbar (3.3.0) lib/rollbar/middleware/rails/rollbar.rb:25:in `block in call'
 - rollbar (3.3.0) lib/rollbar.rb:145:in `scoped'
 - rollbar (3.3.0) lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - better_errors (2.9.1) lib/better_errors/middleware.rb:87:in `protected_app_call'
 - better_errors (2.9.1) lib/better_errors/middleware.rb:82:in `better_errors_call'
 - better_errors (2.9.1) lib/better_errors/middleware.rb:60:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - actionpack (7.0.3) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
 - rollbar (3.3.0) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - actionpack (7.0.3) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - railties (7.0.3) lib/rails/rack/logger.rb:40:in `call_app'
 - railties (7.0.3) lib/rails/rack/logger.rb:25:in `block in call'
 - activesupport (7.0.3) lib/active_support/tagged_logging.rb:114:in `block in tagged'
 - activesupport (7.0.3) lib/active_support/tagged_logging.rb:38:in `tagged'
 - activesupport (7.0.3) lib/active_support/tagged_logging.rb:114:in `tagged'
 - railties (7.0.3) lib/rails/rack/logger.rb:25:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - actionpack (7.0.3) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - actionpack (7.0.3) lib/action_dispatch/middleware/request_id.rb:26:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - rack (2.2.3.1) lib/rack/runtime.rb:22:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - actionpack (7.0.3) lib/action_dispatch/middleware/server_timing.rb:20:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - actionpack (7.0.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - actionpack (7.0.3) lib/action_dispatch/middleware/static.rb:23:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - rack (2.2.3.1) lib/rack/sendfile.rb:110:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - actionpack (7.0.3) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - railties (7.0.3) lib/rails/engine.rb:530:in `call'
 - newrelic_rpm (8.8.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:100:in `call'
 - puma (5.6.4) lib/puma/configuration.rb:252:in `call'
 - puma (5.6.4) lib/puma/request.rb:77:in `block in handle_request'
 - puma (5.6.4) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
 - puma (5.6.4) lib/puma/request.rb:76:in `handle_request'
 - puma (5.6.4) lib/puma/server.rb:441:in `process_client'
 - puma (5.6.4) lib/puma/thread_pool.rb:147:in `block in spawn_thread'

**Comment by blassoto** [comment]
I created a PR with a possible solution, thanks:
https://github.com/zendesk/stronger_parameters/pull/107
