### ISSUE TITLE
ActionController::Base undefined during load

### ISSUE THREAD

**Issue by baschtl** [zendesk/stronger_parameters#26]
We are currently trying to upgrade our Rails application from 3.2.22 to 4.2.3. Running `bundle console` on the upgraded application leads to the following error:

```
    NameError: uninitialized constant ActionController::Base
      /Users/sebastianoelke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/stronger_parameters-2.1.1/lib/stronger_parameters/parameters.rb:176:in `<top (required)>'
      /Users/sebastianoelke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/stronger_parameters-2.1.1/lib/stronger_parameters.rb:4:in `require'
      /Users/sebastianoelke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/stronger_parameters-2.1.1/lib/stronger_parameters.rb:4:in `<top (required)>'
      /Users/sebastianoelke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
      /Users/sebastianoelke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
      /Users/sebastianoelke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
      /Users/sebastianoelke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
      /Users/sebastianoelke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
      /Users/sebastianoelke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
      /Users/sebastianoelke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
      /Users/sebastianoelke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/cli/console.rb:10:in `run'
      /Users/sebastianoelke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/cli.rb:308:in `console'
      /Users/sebastianoelke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/sebastianoelke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/sebastianoelke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/sebastianoelke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/sebastianoelke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
      /Users/sebastianoelke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
      /Users/sebastianoelke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /Users/sebastianoelke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
      /Users/sebastianoelke/.rbenv/versions/2.1.2/bin/bundle:23:in `load'
      /Users/sebastianoelke/.rbenv/versions/2.1.2/bin/bundle:23:in `<main>'

Environment

    Bundler   1.10.6
    Rubygems  2.2.2
    Ruby      2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin14.0]
    GEM_HOME  /Users/sebastianoelke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0
    GEM_PATH  /Users/sebastianoelke/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0:/Users/sebastianoelke/.gem/ruby/2.1.0
    Git       2.3.2 (Apple Git-55)
```

In fact, during load in `StrongerParameters::Parameters` `ActionController` is defined, but `ActionController::Base` is not. Hence, the statement `ActionController::Base.send :include, StrongerParameters::ControllerSupport` fails.

The issue might be that when strong parameters was integrated into Rails 4 an explicit require of `ActionController` was removed that was present in https://github.com/rails/strong_parameters/blob/master/lib/action_controller/parameters.rb.

Any ideas? Probably we only need to require `ActionController::Base`explicitly in `StrongerParameters::Parameters`. What is your opinion about that?

**Comment by grosser** [comment]
yeah add whatever require makes it work ... I guess it relied on action_pack loading ActionController::Base previously ...

**Comment by baschtl** [comment]
@grosser Cool, will write a PR to solve this.
